apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend:app
  labels:
    app: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      conatiners:        
        - name: backend-app
          image: akshayparsade/my_cbz_project:latest
          ports:
            - containerPort: 8080
